import dom1 from "./../../img/slider-houses/dom1.jpg";
import dom2 from "./../../img/slider-houses/dom2.jpg";
import dom3 from "./../../img/slider-houses/dom3.jpg";
import dom4 from "./../../img/slider-houses/dom1.jpg";
import dom5 from "./../../img/slider-houses/dom2.jpg";
import dom6 from "./../../img/slider-houses/dom3.jpg";

const housesAray = [
  {
    id: 0,
    name: "Seaside Serenity Villa",
    description:
      "Discover your own piece of paradise with the Seaside Serenity Villa. With an open floor plan, breathtaking ocean views from every room, and direct access to a pristine sandy beach, this property is the epitome of coastal living.",
    location: "Malibu, California",
    price: "$1,250,000",
    mainImg: dom1,
    images: [dom1, dom1, dom1, dom1],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "2,500 Square Feet",
    keyFeatures: [
      "Expansive oceanfront terrace for outdoor entertaining",
      "Gourmet kitchen with top-of-the-line appliances",
      "Private beach access for morning strolls and sunset views",
      "Master suite with a spa-inspired bathroom and ocean-facing balcony",
      "Private garage and ample storage space",
    ],
    listingPrice: 1250000,
    additionalFees: {
      propertyTransferTax: 25000,
      legalFees: 3000,
      homeInspection: 500,
      propertyInsurance: 1200,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 1250,
      homeownersAssociationFee: 300,
    },
    totalInitialCosts: {
      listingPrice: 1250000,
      additionalFees: 29700,
      downPayment: 250000,
      mortgageAmount: 1000000,
    },
    monthlyExpenses: {
      propertyTaxes: 1250,
      homeownersAssociationFee: 300,
      mortgagePayment: "Varies",
      propertyInsurance: 100,
    },
    buildYear: 2020,
  },
  {
    id: 1,
    name: "Mountain View Retreat",
    description:
      "Escape to the tranquility of Mountain View Retreat. Nestled in the heart of the Rockies, this luxurious cabin offers stunning mountain views, cozy fireplaces, and a private hot tub, perfect for unwinding after a day of adventure.",
    location: "Aspen, Colorado",
    price: "$2,500,000",
    mainImg: dom2,
    images: [dom2, dom2, dom2, dom2],
    bedroomsQuantity: "05-Bedroom",
    bathroomsQuantity: "04-Bath",
    type: "Villa",
    area: "4,000 Square Feet",
    keyFeatures: [
      "Floor-to-ceiling windows with panoramic mountain views",
      "Spacious open-concept living area with vaulted ceilings",
      "Gourmet kitchen with granite countertops and stainless steel appliances",
      "Master suite with a fireplace and private balcony",
      "Heated garage and ski-in/ski-out access",
    ],
    listingPrice: 2500000,
    additionalFees: {
      propertyTransferTax: 50000,
      legalFees: 5000,
      homeInspection: 800,
      propertyInsurance: 1800,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2500,
      homeownersAssociationFee: 450,
    },
    totalInitialCosts: {
      listingPrice: 2500000,
      additionalFees: 57600,
      downPayment: 500000,
      mortgageAmount: 2000000,
    },
    monthlyExpenses: {
      propertyTaxes: 2500,
      homeownersAssociationFee: 450,
      mortgagePayment: "Varies",
      propertyInsurance: 150,
    },
    buildYear: 2018,
  },
  {
    id: 2,
    name: "Urban Oasis Penthouse",
    description:
      "Experience the pinnacle of city living in this sleek and modern Urban Oasis Penthouse. With floor-to-ceiling windows, this property boasts breathtaking skyline views, a private rooftop garden, and access to world-class amenities.",
    location: "New York, New York",
    price: "$3,750,000",
    mainImg: dom3,
    images: [dom3, dom3, dom3, dom3],
    bedroomsQuantity: "03-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,000 Square Feet",
    keyFeatures: [
      "Private rooftop terrace with outdoor kitchen and lounge area",
      "Floor-to-ceiling windows offering panoramic city views",
      "State-of-the-art fitness center and indoor swimming pool",
      "Master suite with a spa-inspired bathroom and walk-in closet",
      "24-hour concierge service and private elevator access",
    ],
    listingPrice: 3750000,
    additionalFees: {
      propertyTransferTax: 75000,
      legalFees: 7000,
      homeInspection: 1000,
      propertyInsurance: 2200,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 3750,
      homeownersAssociationFee: 750,
    },
    totalInitialCosts: {
      listingPrice: 3750000,
      additionalFees: 85200,
      downPayment: 750000,
      mortgageAmount: 3000000,
    },
    monthlyExpenses: {
      propertyTaxes: 3750,
      homeownersAssociationFee: 750,
      mortgagePayment: "Varies",
      propertyInsurance: 185,
    },
    buildYear: 2021,
  },
  {
    id: 3,
    name: "Lakeside Tranquility Estate",
    description:
      "Immerse yourself in nature at the Lakeside Tranquility Estate. This stunning property offers a serene lakeside setting, private dock, and a spacious outdoor living area perfect for entertaining guests and enjoying the natural beauty.",
    location: "Lake Tahoe, California",
    price: "$2,100,000",
    mainImg: dom4,
    images: [dom4, dom4, dom4, dom4],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,500 Square Feet",
    keyFeatures: [
      "Private dock with access to Lake Tahoe",
      "Expansive outdoor deck with fire pit and hot tub",
      "Open-concept living area with hardwood floors and a stone fireplace",
      "Gourmet kitchen with custom cabinetry and marble countertops",
      "Master suite with lake views and a spa-like ensuite",
    ],
    listingPrice: 2100000,
    additionalFees: {
      propertyTransferTax: 42000,
      legalFees: 4500,
      homeInspection: 700,
      propertyInsurance: 1600,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2100,
      homeownersAssociationFee: 350,
    },
    totalInitialCosts: {
      listingPrice: 2100000,
      additionalFees: 47800,
      downPayment: 420000,
      mortgageAmount: 1680000,
    },
    monthlyExpenses: {
      propertyTaxes: 2100,
      homeownersAssociationFee: 350,
      mortgagePayment: "Varies",
      propertyInsurance: 133,
    },
    buildYear: 2015,
  },
  {
    id: 4,
    name: "Desert Horizon Mansion",
    description:
      "Discover luxury living in the heart of the desert with Desert Horizon Mansion. This sprawling estate offers unrivaled privacy, stunning desert vistas, and all the modern comforts you could desire.",
    location: "Scottsdale, Arizona",
    price: "$3,000,000",
    mainImg: dom5,
    images: [dom5, dom5, dom5, dom5],
    bedroomsQuantity: "06-Bedroom",
    bathroomsQuantity: "05-Bath",
    type: "Villa",
    area: "5,000 Square Feet",
    keyFeatures: [
      "Infinity pool with sweeping desert views",
      "Outdoor kitchen and entertainment area",
      "Modern design with floor-to-ceiling windows",
      "Gourmet kitchen with custom finishes",
      "Master suite with private terrace and luxury bathroom",
    ],
    listingPrice: 3000000,
    additionalFees: {
      propertyTransferTax: 60000,
      legalFees: 6000,
      homeInspection: 900,
      propertyInsurance: 2000,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 3000,
      homeownersAssociationFee: 500,
    },
    totalInitialCosts: {
      listingPrice: 3000000,
      additionalFees: 68900,
      downPayment: 600000,
      mortgageAmount: 2400000,
    },
    monthlyExpenses: {
      propertyTaxes: 3000,
      homeownersAssociationFee: 500,
      mortgagePayment: "Varies",
      propertyInsurance: 167,
    },
    buildYear: 2019,
  },
  {
    id: 5,
    name: "Coastal Modern Retreat",
    description:
      "Step into the future of coastal living with Coastal Modern Retreat. Featuring cutting-edge architecture, eco-friendly design, and unbeatable ocean views, this home is the perfect blend of luxury and sustainability.",
    location: "Santa Monica, California",
    price: "$4,200,000",
    mainImg: dom6,
    images: [dom6, dom6, dom6, dom6],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "04-Bath",
    type: "Villa",
    area: "4,500 Square Feet",
    keyFeatures: [
      "Solar panels and energy-efficient appliances",
      "Open floor plan with glass walls that blur indoor and outdoor living",
      "Rooftop garden with ocean views",
      "Gourmet kitchen with custom cabinetry and quartz countertops",
      "Smart home technology throughout",
    ],
    listingPrice: 4200000,
    additionalFees: {
      propertyTransferTax: 84000,
      legalFees: 7500,
      homeInspection: 1000,
      propertyInsurance: 2400,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 4200,
      homeownersAssociationFee: 600,
    },
    totalInitialCosts: {
      listingPrice: 4200000,
      additionalFees: 93900,
      downPayment: 840000,
      mortgageAmount: 3360000,
    },
    monthlyExpenses: {
      propertyTaxes: 4200,
      homeownersAssociationFee: 600,
      mortgagePayment: "Varies",
      propertyInsurance: 200,
    },
    buildYear: 2022,
  },
  {
    id: 6,
    name: "Sunny Beach House",
    description:
      "Enjoy sunny days and sea breezes at the Sunny Beach House. This charming beachside property offers casual elegance, a spacious deck, and stunning ocean views, perfect for a relaxed coastal lifestyle.",
    location: "Laguna Beach, California",
    price: "$1,800,000",
    mainImg: dom1,
    images: [dom1, dom1, dom1, dom1],
    bedroomsQuantity: "03-Bedroom",
    bathroomsQuantity: "02-Bath",
    type: "Villa",
    area: "2,000 Square Feet",
    keyFeatures: [
      "Large deck for outdoor dining and sunbathing",
      "Open-concept living area with ocean views",
      "Well-appointed kitchen with modern appliances",
      "Master bedroom with private balcony",
      "Close proximity to the beach and local amenities",
    ],
    listingPrice: 1800000,
    additionalFees: {
      propertyTransferTax: 36000,
      legalFees: 4000,
      homeInspection: 600,
      propertyInsurance: 1500,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 1800,
      homeownersAssociationFee: 400,
    },
    totalInitialCosts: {
      listingPrice: 1800000,
      additionalFees: 46600,
      downPayment: 360000,
      mortgageAmount: 1440000,
    },
    monthlyExpenses: {
      propertyTaxes: 1800,
      homeownersAssociationFee: 400,
      mortgagePayment: "Varies",
      propertyInsurance: 125,
    },
    buildYear: 2023,
  },
  {
    id: 7,
    name: "Alpine Chalet",
    description:
      "Experience the charm of alpine living at the Alpine Chalet. Located in the picturesque mountains, this cozy retreat offers breathtaking views, rustic charm, and modern comforts for a perfect mountain getaway.",
    location: "Vail, Colorado",
    price: "$2,200,000",
    mainImg: dom2,
    images: [dom2, dom2, dom2, dom2],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,200 Square Feet",
    keyFeatures: [
      "Panoramic mountain views from every room",
      "Cozy fireplace in the living room",
      "Spacious kitchen with high-end appliances",
      "Private balcony off the master suite",
      "Direct access to ski slopes",
    ],
    listingPrice: 2200000,
    additionalFees: {
      propertyTransferTax: 44000,
      legalFees: 5000,
      homeInspection: 700,
      propertyInsurance: 1700,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2200,
      homeownersAssociationFee: 500,
    },
    totalInitialCosts: {
      listingPrice: 2200000,
      additionalFees: 48800,
      downPayment: 440000,
      mortgageAmount: 1760000,
    },
    monthlyExpenses: {
      propertyTaxes: 2200,
      homeownersAssociationFee: 500,
      mortgagePayment: "Varies",
      propertyInsurance: 140,
    },
    buildYear: 2017,
  },
  {
    id: 8,
    name: "City Skyline Loft",
    description:
      "Live in style with the City Skyline Loft. This modern, high-rise loft offers unparalleled city views, luxury finishes, and a prime location in the heart of downtown, perfect for urban living at its finest.",
    location: "Chicago, Illinois",
    price: "$2,800,000",
    mainImg: dom3,
    images: [dom3, dom3, dom3, dom3],
    bedroomsQuantity: "02-Bedroom",
    bathroomsQuantity: "02-Bath",
    type: "Villa",
    area: "2,500 Square Feet",
    keyFeatures: [
      "Expansive windows with stunning city views",
      "Open-concept living and dining area",
      "High-end kitchen with custom finishes",
      "Luxurious master suite with a walk-in closet",
      "Access to building amenities including a gym and rooftop terrace",
    ],
    listingPrice: 2800000,
    additionalFees: {
      propertyTransferTax: 56000,
      legalFees: 6000,
      homeInspection: 800,
      propertyInsurance: 2000,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2800,
      homeownersAssociationFee: 600,
    },
    totalInitialCosts: {
      listingPrice: 2800000,
      additionalFees: 65800,
      downPayment: 560000,
      mortgageAmount: 2240000,
    },
    monthlyExpenses: {
      propertyTaxes: 2800,
      homeownersAssociationFee: 600,
      mortgagePayment: "Varies",
      propertyInsurance: 175,
    },
    buildYear: 2022,
  },
  {
    id: 9,
    name: "Forest Hideaway",
    description:
      "Find peace and solitude at the Forest Hideaway. Nestled in the heart of a lush forest, this secluded property offers a cozy retreat with modern amenities and plenty of space to unwind and reconnect with nature.",
    location: "Portland, Oregon",
    price: "$1,700,000",
    mainImg: dom4,
    images: [dom4, dom4, dom4, dom4],
    bedroomsQuantity: "03-Bedroom",
    bathroomsQuantity: "02-Bath",
    type: "Villa",
    area: "2,800 Square Feet",
    keyFeatures: [
      "Private wooded setting with abundant wildlife",
      "Open floor plan with large windows",
      "Spacious deck for outdoor living",
      "Well-equipped kitchen with modern appliances",
      "Master suite with private balcony",
    ],
    listingPrice: 1700000,
    additionalFees: {
      propertyTransferTax: 34000,
      legalFees: 4000,
      homeInspection: 600,
      propertyInsurance: 1400,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 1700,
      homeownersAssociationFee: 400,
    },
    totalInitialCosts: {
      listingPrice: 1700000,
      additionalFees: 46400,
      downPayment: 340000,
      mortgageAmount: 1360000,
    },
    monthlyExpenses: {
      propertyTaxes: 1700,
      homeownersAssociationFee: 400,
      mortgagePayment: "Varies",
      propertyInsurance: 120,
    },
    buildYear: 2019,
  },
  {
    id: 10,
    name: "Desert Oasis Villa",
    description:
      "Discover tranquility in the Desert Oasis Villa. This expansive property offers stunning desert views, luxurious amenities, and a perfect blend of modern comfort and natural beauty.",
    location: "Palm Springs, California",
    price: "$3,300,000",
    mainImg: dom5,
    images: [dom5, dom5, dom5, dom5],
    bedroomsQuantity: "05-Bedroom",
    bathroomsQuantity: "04-Bath",
    type: "Villa",
    area: "4,000 Square Feet",
    keyFeatures: [
      "Infinity pool with breathtaking desert views",
      "Spacious outdoor living area with fire pit",
      "Modern kitchen with high-end appliances",
      "Luxurious master suite with private terrace",
      "Close proximity to golf courses and spas",
    ],
    listingPrice: 3300000,
    additionalFees: {
      propertyTransferTax: 66000,
      legalFees: 7000,
      homeInspection: 900,
      propertyInsurance: 2100,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 3300,
      homeownersAssociationFee: 500,
    },
    totalInitialCosts: {
      listingPrice: 3300000,
      additionalFees: 76100,
      downPayment: 660000,
      mortgageAmount: 2640000,
    },
    monthlyExpenses: {
      propertyTaxes: 3300,
      homeownersAssociationFee: 500,
      mortgagePayment: "Varies",
      propertyInsurance: 180,
    },
    buildYear: 2020,
  },
  {
    id: 11,
    name: "Bayfront Mansion",
    description:
      "Experience luxury living with unparalleled bay views at Bayfront Mansion. This stunning property offers a blend of modern elegance and serene waterfront living.",
    location: "San Francisco, California",
    price: "$4,500,000",
    mainImg: dom6,
    images: [dom6, dom6, dom6, dom6],
    bedroomsQuantity: "06-Bedroom",
    bathroomsQuantity: "05-Bath",
    type: "Villa",
    area: "5,000 Square Feet",
    keyFeatures: [
      "Private dock with direct bay access",
      "Expansive windows with panoramic bay views",
      "State-of-the-art kitchen and luxury finishes",
      "Master suite with a private terrace and spa-like bathroom",
      "Close to fine dining and cultural attractions",
    ],
    listingPrice: 4500000,
    additionalFees: {
      propertyTransferTax: 90000,
      legalFees: 8000,
      homeInspection: 1000,
      propertyInsurance: 2500,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 4500,
      homeownersAssociationFee: 800,
    },
    totalInitialCosts: {
      listingPrice: 4500000,
      additionalFees: 96500,
      downPayment: 900000,
      mortgageAmount: 3600000,
    },
    monthlyExpenses: {
      propertyTaxes: 4500,
      homeownersAssociationFee: 800,
      mortgagePayment: "Varies",
      propertyInsurance: 225,
    },
    buildYear: 2021,
  },
  {
    id: 12,
    name: "Rural Retreat",
    description:
      "Find peace and quiet at the Rural Retreat. This charming property offers a serene country setting with modern amenities and a cozy atmosphere perfect for relaxation.",
    location: "Napa Valley, California",
    price: "$1,900,000",
    mainImg: dom1,
    images: [dom1, dom1, dom1, dom1],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,200 Square Feet",
    keyFeatures: [
      "Spacious grounds with beautiful gardens",
      "Open-concept living area with modern appliances",
      "Large deck for outdoor entertaining",
      "Master suite with a private balcony",
      "Close proximity to local vineyards and wineries",
    ],
    listingPrice: 1900000,
    additionalFees: {
      propertyTransferTax: 38000,
      legalFees: 4500,
      homeInspection: 700,
      propertyInsurance: 1600,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 1900,
      homeownersAssociationFee: 400,
    },
    totalInitialCosts: {
      listingPrice: 1900000,
      additionalFees: 47000,
      downPayment: 380000,
      mortgageAmount: 1520000,
    },
    monthlyExpenses: {
      propertyTaxes: 1900,
      homeownersAssociationFee: 400,
      mortgagePayment: "Varies",
      propertyInsurance: 130,
    },
    buildYear: 2022,
  },
  {
    id: 13,
    name: "Ski Lodge",
    description:
      "Enjoy the ultimate winter getaway at the Ski Lodge. Located near prime ski slopes, this property offers cozy accommodations, stunning mountain views, and easy access to winter sports.",
    location: "Jackson Hole, Wyoming",
    price: "$2,400,000",
    mainImg: dom2,
    images: [dom2, dom2, dom2, dom2],
    bedroomsQuantity: "05-Bedroom",
    bathroomsQuantity: "04-Bath",
    type: "Villa",
    area: "3,800 Square Feet",
    keyFeatures: [
      "Direct access to ski slopes",
      "Cozy fireplace and open-concept living area",
      "Spacious kitchen with modern appliances",
      "Master suite with mountain views",
      "Large deck and hot tub for après-ski relaxation",
    ],
    listingPrice: 2400000,
    additionalFees: {
      propertyTransferTax: 48000,
      legalFees: 5500,
      homeInspection: 800,
      propertyInsurance: 1800,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2400,
      homeownersAssociationFee: 500,
    },
    totalInitialCosts: {
      listingPrice: 2400000,
      additionalFees: 54800,
      downPayment: 480000,
      mortgageAmount: 1920000,
    },
    monthlyExpenses: {
      propertyTaxes: 2400,
      homeownersAssociationFee: 500,
      mortgagePayment: "Varies",
      propertyInsurance: 150,
    },
    buildYear: 2018,
  },
  {
    id: 14,
    name: "Urban Loft",
    description:
      "Live in the heart of the city with the Urban Loft. This chic, modern loft offers stylish finishes, open spaces, and a prime location close to entertainment and dining options.",
    location: "San Diego, California",
    price: "$2,500,000",
    mainImg: dom3,
    images: [dom3, dom3, dom3, dom3],
    bedroomsQuantity: "03-Bedroom",
    bathroomsQuantity: "02-Bath",
    type: "Villa",
    area: "2,800 Square Feet",
    keyFeatures: [
      "Expansive windows with city views",
      "Open floor plan with modern finishes",
      "High-end kitchen with custom cabinetry",
      "Master suite with a walk-in closet",
      "Access to building amenities including a rooftop terrace",
    ],
    listingPrice: 2500000,
    additionalFees: {
      propertyTransferTax: 50000,
      legalFees: 6000,
      homeInspection: 700,
      propertyInsurance: 2000,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2500,
      homeownersAssociationFee: 600,
    },
    totalInitialCosts: {
      listingPrice: 2500000,
      additionalFees: 65200,
      downPayment: 500000,
      mortgageAmount: 2000000,
    },
    monthlyExpenses: {
      propertyTaxes: 2500,
      homeownersAssociationFee: 600,
      mortgagePayment: "Varies",
      propertyInsurance: 175,
    },
    buildYear: 2023,
  },
  {
    id: 15,
    name: "Secluded Retreat",
    description:
      "Find peace and privacy at the Secluded Retreat. This tranquil property offers a serene environment, lush surroundings, and modern amenities for a perfect escape from the city.",
    location: "Asheville, North Carolina",
    price: "$1,950,000",
    mainImg: dom4,
    images: [dom4, dom4, dom4, dom4],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,000 Square Feet",
    keyFeatures: [
      "Private wooded setting with extensive gardens",
      "Open-concept living area with modern finishes",
      "Large deck for outdoor entertaining",
      "Well-equipped kitchen with high-end appliances",
      "Master suite with a private balcony",
    ],
    listingPrice: 1950000,
    additionalFees: {
      propertyTransferTax: 39000,
      legalFees: 4500,
      homeInspection: 600,
      propertyInsurance: 1500,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 1950,
      homeownersAssociationFee: 400,
    },
    totalInitialCosts: {
      listingPrice: 1950000,
      additionalFees: 47500,
      downPayment: 390000,
      mortgageAmount: 1560000,
    },
    monthlyExpenses: {
      propertyTaxes: 1950,
      homeownersAssociationFee: 400,
      mortgagePayment: "Varies",
      propertyInsurance: 130,
    },
    buildYear: 2022,
  },
  {
    id: 16,
    name: "Desert Paradise",
    description:
      "Embrace desert living at its finest with Desert Paradise. This luxury estate offers stunning desert vistas, a private pool, and modern amenities in a tranquil setting.",
    location: "Las Vegas, Nevada",
    price: "$2,800,000",
    mainImg: dom5,
    images: [dom5, dom5, dom5, dom5],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,800 Square Feet",
    keyFeatures: [
      "Infinity pool with panoramic desert views",
      "Spacious outdoor living area with a fire pit",
      "Modern kitchen with high-end appliances",
      "Luxurious master suite with a private terrace",
      "Close proximity to entertainment and dining options",
    ],
    listingPrice: 2800000,
    additionalFees: {
      propertyTransferTax: 56000,
      legalFees: 6000,
      homeInspection: 800,
      propertyInsurance: 2000,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2800,
      homeownersAssociationFee: 600,
    },
    totalInitialCosts: {
      listingPrice: 2800000,
      additionalFees: 64600,
      downPayment: 560000,
      mortgageAmount: 2240000,
    },
    monthlyExpenses: {
      propertyTaxes: 2800,
      homeownersAssociationFee: 600,
      mortgagePayment: "Varies",
      propertyInsurance: 175,
    },
    buildYear: 2021,
  },
  {
    id: 17,
    name: "Countryside Estate",
    description:
      "Escape to the Countryside Estate, a charming property offering expansive grounds, modern amenities, and a serene rural setting perfect for relaxing and enjoying the natural beauty.",
    location: "Austin, Texas",
    price: "$1,750,000",
    mainImg: dom1,
    images: [dom1, dom1, dom1, dom1],
    bedroomsQuantity: "03-Bedroom",
    bathroomsQuantity: "02-Bath",
    type: "House",
    area: "2,500 Square Feet",
    keyFeatures: [
      "Spacious grounds with gardens and open fields",
      "Modern kitchen with high-end appliances",
      "Large deck for outdoor living and entertaining",
      "Master suite with private balcony",
      "Close proximity to local amenities and attractions",
    ],
    listingPrice: 1750000,
    additionalFees: {
      propertyTransferTax: 35000,
      legalFees: 4000,
      homeInspection: 600,
      propertyInsurance: 1500,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 1750,
      homeownersAssociationFee: 400,
    },
    totalInitialCosts: {
      listingPrice: 1750000,
      additionalFees: 41900,
      downPayment: 350000,
      mortgageAmount: 1400000,
    },
    monthlyExpenses: {
      propertyTaxes: 1750,
      homeownersAssociationFee: 400,
      mortgagePayment: "Varies",
      propertyInsurance: 120,
    },
    buildYear: 2020,
  },
  {
    id: 18,
    name: "Mountain View Lodge",
    description:
      "Discover the perfect mountain retreat with Mountain View Lodge. Offering stunning views, cozy interiors, and modern amenities, this property is ideal for those seeking a peaceful getaway in the mountains.",
    location: "Aspen, Colorado",
    price: "$2,600,000",
    mainImg: dom2,
    images: [dom2, dom2, dom2, dom2],
    bedroomsQuantity: "04-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,600 Square Feet",
    keyFeatures: [
      "Panoramic mountain views from every room",
      "Cozy fireplace and open-concept living area",
      "Spacious kitchen with high-end appliances",
      "Master suite with a private balcony",
      "Direct access to hiking trails and ski slopes",
    ],
    listingPrice: 2600000,
    additionalFees: {
      propertyTransferTax: 52000,
      legalFees: 6000,
      homeInspection: 800,
      propertyInsurance: 2000,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2600,
      homeownersAssociationFee: 500,
    },
    totalInitialCosts: {
      listingPrice: 2600000,
      additionalFees: 60800,
      downPayment: 520000,
      mortgageAmount: 2080000,
    },
    monthlyExpenses: {
      propertyTaxes: 2600,
      homeownersAssociationFee: 500,
      mortgagePayment: "Varies",
      propertyInsurance: 175,
    },
    buildYear: 2022,
  },
  {
    id: 19,
    name: "Lakefront Cabin",
    description:
      "Experience lakeside tranquility with Lakefront Cabin. This charming cabin offers stunning lake views, cozy interiors, and modern amenities for a perfect retreat in nature.",
    location: "Lake Tahoe, California",
    price: "$2,000,000",
    mainImg: dom1,
    images: [dom1, dom1, dom1, dom1],
    bedroomsQuantity: "03-Bedroom",
    bathroomsQuantity: "02-Bath",
    type: "Villa",
    area: "2,800 Square Feet",
    keyFeatures: [
      "Stunning lake views from every room",
      "Cozy fireplace and open-concept living area",
      "Spacious deck for outdoor living",
      "Well-equipped kitchen with modern appliances",
      "Master suite with a private balcony",
    ],
    listingPrice: 2000000,
    additionalFees: {
      propertyTransferTax: 40000,
      legalFees: 4500,
      homeInspection: 700,
      propertyInsurance: 1600,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 2000,
      homeownersAssociationFee: 400,
    },
    totalInitialCosts: {
      listingPrice: 2000000,
      additionalFees: 47700,
      downPayment: 400000,
      mortgageAmount: 1600000,
    },
    monthlyExpenses: {
      propertyTaxes: 2000,
      homeownersAssociationFee: 400,
      mortgagePayment: "Varies",
      propertyInsurance: 140,
    },
    buildYear: 2023,
  },
  {
    id: 20,
    name: "Luxury Penthouse",
    description:
      "Experience ultimate luxury with the Luxury Penthouse. Offering expansive city views, top-of-the-line finishes, and unparalleled amenities, this property redefines urban living.",
    location: "New York, New York",
    price: "$5,000,000",
    mainImg: dom3,
    images: [dom3, dom3, dom3, dom3],
    bedroomsQuantity: "03-Bedroom",
    bathroomsQuantity: "03-Bath",
    type: "Villa",
    area: "3,500 Square Feet",
    keyFeatures: [
      "Panoramic city views from every room",
      "Open-concept living area with high-end finishes",
      "State-of-the-art kitchen with premium appliances",
      "Luxurious master suite with private terrace",
      "Access to exclusive building amenities including a rooftop garden",
    ],
    listingPrice: 5000000,
    additionalFees: {
      propertyTransferTax: 100000,
      legalFees: 10000,
      homeInspection: 1200,
      propertyInsurance: 3000,
      mortgageFees: "Varies",
    },
    monthlyCosts: {
      propertyTaxes: 5000,
      homeownersAssociationFee: 1000,
    },
    totalInitialCosts: {
      listingPrice: 5000000,
      additionalFees: 114200,
      downPayment: 1000000,
      mortgageAmount: 4000000,
    },
    monthlyExpenses: {
      propertyTaxes: 5000,
      homeownersAssociationFee: 1000,
      mortgagePayment: "Varies",
      propertyInsurance: 250,
    },
    buildYear: 2024,
  },
];

export { housesAray };
